name: Node.js CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - run: npm ci
      - run: npm test
        env:
          CI: true
      - run: npm run docs --if-present
      - name: deploy docs
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          SSH: true
          CLEAN: true
          BRANCH: gh-pages
          FOLDER: docs
